// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10x_cookbook_backend.Data;

#nullable disable

namespace _10x_cookbook_backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525155743_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_10x_cookbook_backend.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSpiceOrStaple")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711001"),
                            IsSpiceOrStaple = false,
                            Name = "pomidor"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711002"),
                            IsSpiceOrStaple = false,
                            Name = "cebula"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711003"),
                            IsSpiceOrStaple = false,
                            Name = "czosnek"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711004"),
                            IsSpiceOrStaple = false,
                            Name = "makaron"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711005"),
                            IsSpiceOrStaple = true,
                            Name = "oliwa z oliwek"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711006"),
                            IsSpiceOrStaple = true,
                            Name = "bazylia"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711007"),
                            IsSpiceOrStaple = false,
                            Name = "pierś z kurczaka"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711008"),
                            IsSpiceOrStaple = false,
                            Name = "ryż"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711009"),
                            IsSpiceOrStaple = false,
                            Name = "marchewka"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711010"),
                            IsSpiceOrStaple = false,
                            Name = "ziemniaki"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711011"),
                            IsSpiceOrStaple = true,
                            Name = "sól"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711012"),
                            IsSpiceOrStaple = true,
                            Name = "pieprz"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711013"),
                            IsSpiceOrStaple = true,
                            Name = "masło"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711014"),
                            IsSpiceOrStaple = false,
                            Name = "mleko"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711015"),
                            IsSpiceOrStaple = true,
                            Name = "mąka pszenna"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711016"),
                            IsSpiceOrStaple = false,
                            Name = "jajko"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711017"),
                            IsSpiceOrStaple = false,
                            Name = "ser żółty"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711018"),
                            IsSpiceOrStaple = true,
                            Name = "papryka słodka"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711019"),
                            IsSpiceOrStaple = true,
                            Name = "cukier"
                        },
                        new
                        {
                            Id = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711020"),
                            IsSpiceOrStaple = false,
                            Name = "cytryna"
                        });
                });

            modelBuilder.Entity("_10x_cookbook_backend.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822001"),
                            Instructions = "Ugotuj makaron al dente. Na patelni rozgrzej oliwę z oliwek, zeszklij pokrojoną cebulę i posiekany czosnek. Dodaj rozgniecione pomidory, sól, pieprz i bazylię. Duś przez 10 minut. Wymieszaj makaron z sosem i posyp serem.",
                            IsPublic = true,
                            Title = "Makaron z sosem pomidorowym"
                        },
                        new
                        {
                            Id = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822002"),
                            Instructions = "Ugotuj ryż. Pierś z kurczaka pokrój w kostkę, dopraw solą, pieprzem i słodką papryką, a następnie usmaż na oliwie z oliwek. Dodaj pokrojoną cebulę i marchewkę. Smaż przez 10 minut. Podawaj kurczaka z warzywami na ryżu.",
                            IsPublic = true,
                            Title = "Ryż z kurczakiem i warzywami"
                        },
                        new
                        {
                            Id = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822003"),
                            Instructions = "Rozgrzej masło na patelni. Wbij jajka, posól, popieprz i smaż na wolnym ogniu, ciągle mieszając, aż do uzyskania pożądanej konsystencji.",
                            IsPublic = true,
                            Title = "Jajecznica na maśle"
                        });
                });

            modelBuilder.Entity("_10x_cookbook_backend.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822001"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711004"),
                            Quantity = "200g"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822001"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711001"),
                            Quantity = "3 sztuki"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822001"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711005"),
                            Quantity = "2 łyżki"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822001"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711002"),
                            Quantity = "1 sztuka"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822001"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711003"),
                            Quantity = "2 ząbki"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822001"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711006"),
                            Quantity = "kilka listków"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822001"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711011"),
                            Quantity = "do smaku"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822001"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711012"),
                            Quantity = "do smaku"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822002"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711008"),
                            Quantity = "150g"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822002"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711007"),
                            Quantity = "300g"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822002"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711009"),
                            Quantity = "1 sztuka"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822002"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711002"),
                            Quantity = "1 sztuka"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822002"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711005"),
                            Quantity = "2 łyżki"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822002"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711018"),
                            Quantity = "1 łyżeczka"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822002"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711011"),
                            Quantity = "szczypta"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822002"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711012"),
                            Quantity = "szczypta"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822003"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711016"),
                            Quantity = "3 sztuki"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822003"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711013"),
                            Quantity = "1 łyżka"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822003"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711011"),
                            Quantity = "szczypta"
                        },
                        new
                        {
                            RecipeId = new Guid("9d9d2022-36fa-4684-93ef-ecf2dc822003"),
                            IngredientId = new Guid("4d4d1011-25ef-4573-82ef-dcf1db711012"),
                            Quantity = "szczypta"
                        });
                });

            modelBuilder.Entity("_10x_cookbook_backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_10x_cookbook_backend.Models.Recipe", b =>
                {
                    b.HasOne("_10x_cookbook_backend.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("_10x_cookbook_backend.Models.RecipeIngredient", b =>
                {
                    b.HasOne("_10x_cookbook_backend.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10x_cookbook_backend.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("_10x_cookbook_backend.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("_10x_cookbook_backend.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("_10x_cookbook_backend.Models.User", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
